# permissions for end users to edit apps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: app-operator
    app.kubernetes.io/managed-by: kustomize
  name: app-editor-role
rules:
- apiGroups:
  - apps.wlin.cn
  resources:
  - apps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.wlin.cn
  resources:
  - apps/status
  verbs:
  - get
