apiVersion: apps.wlin.cn/v1
kind: App
metadata:
  labels:
    app.kubernetes.io/name: app-operator
    app.kubernetes.io/managed-by: kustomize
  name: app-sample
spec:
  # TODO(user): Add fields here
