apiVersion: apps.wlin.cn/v1
kind: App
metadata:
  name: nginx-sample
  namespace: app-operator-system
  labels:
    app: nginx
spec:
  deployment:
    replicas: 11
    selector:
      matchLabels:
        app: nginx
    template:
      metadata:
      # labels:
      #   app: nginx
      spec:
        containers:
        - name: nginx
          image: nginx:alpine
          ports:
          - containerPort: 80
  service:
    type: NodePort
    ports:
    - port: 80
      targetPort: 80
      nodePort: 30080

